version: '3.3'

services:
  contacts:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    restart: always
    container_name: Kontaktai

  patientcrud:
    build: .
    depends_on: 
      - contacts
    ports:
      - "80:8080"
    restart: always
    container_name: patientCrud

  
